In [4]:
import numpy as np

In [5]:
a=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
a

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [6]:
b=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])

In [7]:
b

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [8]:
b.shape

(3, 3, 2)

In [9]:
#three ways of accessing element in array
a[1,0:3:1]

array([9, 3, 5])

In [10]:
a[1][0]

9

In [11]:
a[1,0]

9

In [12]:
a[0:4:1,2:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [13]:
b[0,0,0:]

array([ 4, 41])

In [14]:
b[2,1,1]

91

In [15]:
b[1:3:1,1,1]

array([11, 91])

In [16]:
a[:,-1:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [17]:
b[1:3,1:3,1]

array([[ 11,  51],
       [ 91, 131]])

In [18]:

b[1:3,1:3,0]

array([[ 1,  5],
       [ 9, 13]])

In [19]:
b[1:2,1:3,0:2:1]

array([[[ 1, 11],
        [ 5, 51]]])

In [20]:
#list cannot be added to integer
x=[3,5,9]
x+5

TypeError: can only concatenate list (not "int") to list

In [21]:
#arrays can perform scalar operation
a+5

array([[ 8, 13,  9],
       [14,  8, 10],
       [16, 20, 22],
       [24, 36, 13]])

In [22]:
#arrays perform mutable operation 
#del from array is not possible like "del a[0]"
a[0]=13

In [23]:
a

array([[13, 13, 13],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [24]:
a[0,:]=[30,48,50]
a

array([[30, 48, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [25]:
a[0:4:1,1]=[5,6,7,8]
a

array([[30,  5, 50],
       [ 9,  6,  5],
       [11,  7, 17],
       [19,  8,  8]])

In [26]:
a[0:4:1,1:]=[[5],[6],[7],[8]]
a

array([[30,  5,  5],
       [ 9,  6,  6],
       [11,  7,  7],
       [19,  8,  8]])

In [28]:
#function to add a row in array
np.append(a,[[1,1,1]],axis=0) #zero to add rowwise

array([[30,  5,  5],
       [ 9,  6,  6],
       [11,  7,  7],
       [19,  8,  8],
       [ 1,  1,  1]])

In [33]:
np.append(a, [[1],[1],[1],[1]], axis=1) #one to add columnwise

array([[30,  5,  5,  1],
       [ 9,  6,  6,  1],
       [11,  7,  7,  1],
       [19,  8,  8,  1]])

In [35]:
#to delete row in array
np.delete(a,1,0)

array([[30,  5,  5],
       [11,  7,  7],
       [19,  8,  8]])

In [36]:
np.delete(a,1,1)

array([[30,  5],
       [ 9,  6],
       [11,  7],
       [19,  8]])

In [38]:
#delete column
np.delete(a,3,axis=0)

array([[30,  5,  5],
       [ 9,  6,  6],
       [11,  7,  7]])

In [39]:
a.shape

(4, 3)

In [40]:
a.size

12

In [41]:
#reshape function to chaange the shape of array
a.reshape(6,2)

array([[30,  5],
       [ 5,  9],
       [ 6,  6],
       [11,  7],
       [ 7, 19],
       [ 8,  8]])

In [42]:
a.dtype

dtype('int32')

In [43]:
a1=np.array([3.5,3,7])
a1


array([3.5, 3. , 7. ])

In [44]:
a1.dtype

dtype('float64')

In [45]:
#to change datatype from float to integer
a1.astype('uint16')

array([3, 3, 7], dtype=uint16)

In [46]:
#statistical peration functions
a.mean(axis=1)

array([13.33333333,  7.        ,  8.33333333, 11.66666667])

In [50]:
a.sum(axis=1)

array([40, 21, 25, 35])

In [51]:
a.std(axis=1)

array([11.78511302,  1.41421356,  1.88561808,  5.18544973])

In [ ]:
#nutshell
##we create arrays
#np.array()
#np.ones()
#np.zeros()
#np.arange()
#np.random()
##arrays have some attributes and functions

In [7]:
np.arange(1,11,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [53]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [54]:
np.random.randint(1,15,[3,4])

array([[ 9, 12,  4, 11],
       [ 2,  3,  7,  9],
       [14,  6,  9, 10]])

In [10]:
np.random.randint(1,15,1)  
#last value defines the dimension of array

array([6])

In [11]:
np.random.randint(22,56,[4,3,2])

array([[[36, 35],
        [32, 47],
        [38, 53]],

       [[48, 50],
        [52, 51],
        [51, 33]],

       [[53, 36],
        [35, 45],
        [23, 40]],

       [[42, 41],
        [47, 28],
        [27, 25]]])

In [18]:
#ways to stabilise the randomness
np.random.seed(12)
np.random.randint(1,15,[3,4])

array([[12, 12,  7, 14],
       [ 2,  3,  4,  4],
       [13,  1,  7,  2]])

In [19]:
#rand generates random numbers between 0.0 to 1.0
np.random.rand(3,4)

array([[0.90071485, 0.03342143, 0.95694934, 0.13720932],
       [0.28382835, 0.60608318, 0.94422514, 0.85273554],
       [0.00225923, 0.52122603, 0.55203763, 0.48537741]])

In [15]:
import numpy as np

In [5]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#range function works only for integer values
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
r=np.loadtxt('somedata.txt', dtype=str)
r

array(['Hi', 'this', 'is', 'not', 'a', 'python', 'file.'], dtype='<U6')

In [23]:
r=np.loadtxt('moredata.txt')
r

array([[45., 56., 78., 99.],
       [23., 11., 22., 44.]])

In [26]:
p=np.random.rand(3,4)

In [27]:
#used to create a new file
np.savetxt('new.txt',p,delimiter=' ')