In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:

#create array of even integers from 10 to50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
np.random.randint(0,8,(3,3))

array([[0, 5, 0],
       [6, 2, 5],
       [1, 0, 4]])

In [9]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#create 3*3 identity matrix
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:

#generate random number between 0 and 1
np.random.rand(1)

array([0.52338359])

In [15]:
#use numpy to generate normal distribution of 25 number
np.random.randn(25)

array([ 1.25938194,  0.119036  , -1.22589317,  0.73773669,  2.57871333,
       -0.10758805,  0.34509188, -0.08237597,  0.74794761,  1.15508581,
       -1.28195137,  0.96538245, -1.293863  , -0.82881181,  0.58667276,
        0.76868076,  1.37051174,  0.48375984, -1.93060587,  1.01122562,
        1.73357992, -0.94808757, -0.89110654, -0.43446758, -0.42842953])

In [16]:
np.random.rand(10,10)

array([[0.80557747, 0.1241217 , 0.00835036, 0.48215731, 0.90807359,
        0.81907519, 0.67331621, 0.7459708 , 0.58162161, 0.43143055],
       [0.00647344, 0.15955507, 0.78534059, 0.93796261, 0.14594925,
        0.75217966, 0.28024588, 0.42776133, 0.29733055, 0.56227339],
       [0.82170879, 0.95396936, 0.94919856, 0.61550671, 0.27131251,
        0.4993444 , 0.08321471, 0.55891881, 0.91211954, 0.99750739],
       [0.17431064, 0.49502838, 0.46587603, 0.16002732, 0.85729804,
        0.18902804, 0.57645815, 0.33075565, 0.65707727, 0.10432822],
       [0.2897175 , 0.55216027, 0.41875142, 0.24686464, 0.21832425,
        0.49543539, 0.01591476, 0.57823618, 0.21886866, 0.99643552],
       [0.84333411, 0.82992112, 0.61979011, 0.63441662, 0.01631058,
        0.81031611, 0.21618652, 0.54186336, 0.64021882, 0.3368896 ],
       [0.36724651, 0.89629091, 0.94960905, 0.17654688, 0.05098158,
        0.8931185 , 0.36006406, 0.40321194, 0.65868319, 0.73383838],
       [0.86983559, 0.06685223, 0.6017504

In [18]:
k=np.arange(0.01,1.01,0.01).reshape(10,10)

In [19]:
k.sum(axis=1)

array([0.55, 1.55, 2.55, 3.55, 4.55, 5.55, 6.55, 7.55, 8.55, 9.55])